[package]
name = "proxer"
version = "0.1.0"
authors = ["souryo <dev.souryo@gmail.com>"]
license = "MIT"

[dependencies]
log = "0.3"
hyper = "0.10"
hyper-native-tls = "0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
