[package]
name = "proxer"
version = "0.1.0"
authors = ["souryo <dev.souryo@gmail.com>"]
license = "MIT"

[dependencies]
log = "0.3"
hyper = "0.10"
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"
